# Generated by Django 6.0.7 on 2026-07-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.CharField(help_text='Short teaser shown on the cards', max_length=300)),
                ('problem', models.TextField(help_text='What problem was being solved')),
                ('architecture', models.TextField(help_text='How it was built')),
                ('outcome', models.TextField(help_text="Result / what you'd do differently")),
                ('tech_stack', models.CharField(help_text='Comma-separated, e.g. dbt, Airflow, Terraform', max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
