# Generated by Django 6.0.7 on 2026-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('context', models.TextField(help_text='What situation led to this decision')),
                ('decision', models.TextField(help_text='What was decided')),
                ('consequences', models.TextField(help_text='Trade-offs and results')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ADR',
                'verbose_name_plural': 'ADRs',
                'ordering': ['-created_at'],
            },
        ),
    ]
