# Generated by Django 6.0.7 on 2026-07-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_adr'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repo URL to import metadata/README from'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='readme_content',
            field=models.TextField(blank=True, help_text='Auto-fetched from GitHub — raw README, not editable here'),
        ),
    ]
