# Generated by Django 6.0.7 on 2026-07-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_casestudy_github_url_casestudy_readme_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='pdf_document',
            field=models.FileField(blank=True, help_text='Full case study write-up as a PDF', null=True, upload_to='case_study_pdfs/'),
        ),
    ]
