# Generated by Django 6.0.7 on 2026-07-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_casestudy_pdf_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('dnd', 'Do Not Disturb')], default='active', max_length=10)),
                ('now_building', models.CharField(help_text="Shown in the 'Now building' banner on the homepage", max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Profile status',
            },
        ),
    ]
