# Generated by Django 6.0.7 on 2026-07-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestatus',
            name='resume_pdf',
            field=models.FileField(blank=True, help_text='Your current CV/resume as a PDF', null=True, upload_to='resume/'),
        ),
    ]
