# Generated by Django 6.0.7 on 2026-07-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_profilestatus_resume_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestatus',
            name='about_text',
            field=models.TextField(blank=True, help_text='Shown in the About section on the homepage'),
        ),
    ]
