# Generated by Django 6.0.7 on 2026-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_profilestatus_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestatus',
            name='profile_photo',
            field=models.FileField(blank=True, help_text='Your profile photo (shown in the hero avatar circle)', null=True, upload_to='profile/'),
        ),
    ]
