# Generated by Django 6.0.7 on 2026-07-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_profilestatus_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestatus',
            name='headline_highlight',
            field=models.CharField(blank=True, help_text='Second line of the hero headline (shown in the blue gradient)', max_length=200),
        ),
        migrations.AddField(
            model_name='profilestatus',
            name='headline_main',
            field=models.CharField(blank=True, help_text='First line of the hero headline (plain text)', max_length=200),
        ),
        migrations.AddField(
            model_name='profilestatus',
            name='subtext',
            field=models.TextField(blank=True, help_text='Paragraph shown below the hero headline'),
        ),
    ]
