# Generated by Django 6.0.7 on 2026-07-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_profilestatus_headline_highlight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilestatus',
            name='headline_highlight',
        ),
        migrations.AlterField(
            model_name='profilestatus',
            name='headline_main',
            field=models.CharField(help_text='Full hero headline text', max_length=300),
        ),
    ]
