# Generated by Django 6.0.7 on 2026-07-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='pipeline_name',
            field=models.CharField(default='job_market', max_length=50),
        ),
    ]
