# Generated by Django 6.0.7 on 2026-08-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_visitorsession_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('dag_run_id', models.CharField(blank=True, max_length=150)),
                ('error_summary', models.TextField()),
                ('diagnosis', models.TextField()),
                ('suggested_fix', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('auto_retried', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('dedup', 'Deduplication'), ('null_fill', 'Null Fill'), ('outlier_flag', 'Outlier Flagged'), ('schema_drift', 'Schema Drift Detected')], max_length=20)),
                ('rows_affected', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('arxiv', 'arXiv'), ('github', 'GitHub'), ('hackernews', 'Hacker News')], max_length=20)),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('topic_tags', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField()),
                ('score', models.IntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolAdoptionTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('snapshot_date', models.DateField()),
                ('download_count', models.BigIntegerField()),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('tool_name', 'snapshot_date')},
            },
        ),
    ]
