# Generated by Django 6.0.7 on 2026-08-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_agentdiagnosis_dataqualityaction_researchsignal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchsignal',
            name='source',
            field=models.CharField(choices=[('arxiv', 'arXiv'), ('github', 'GitHub'), ('hackernews', 'Hacker News'), ('semantic_scholar', 'Semantic Scholar'), ('openalex', 'OpenAlex'), ('crossref', 'Crossref'), ('dblp', 'DBLP'), ('hf_papers', 'Hugging Face Papers'), ('zenodo', 'Zenodo')], max_length=20),
        ),
    ]
