# Generated by Django 6.0.7 on 2026-08-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_keyachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='include_in_pdf',
            field=models.BooleanField(default=True, help_text='Show this role in the downloadable CV PDF'),
        ),
    ]
