# Generated by Django 6.0.7 on 2026-08-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_experience_include_in_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this role on the website'),
        ),
    ]
