# Generated by Django 6.0.7 on 2026-09-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_experience_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(choices=[('native', 'Native'), ('full_professional', 'Fluent (C1)'), ('professional', 'Professional Working Proficiency (B2)'), ('intermediate', 'Intermediate (B1)'), ('basic', 'Basic (A2)'), ('learning', 'A1–B1 (Ongoing)')], max_length=30),
        ),
    ]
