# Generated by Django 6.0.7 on 2026-09-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_alter_language_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedCVPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_data', models.BinaryField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
