# Generated by Django 6.0.7 on 2026-10-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_cachedcvpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Uppsala, Sweden', max_length=200),
        ),
        migrations.CreateModel(
            name='ProfileEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='analytics.profile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('messaging_app', models.CharField(choices=[('none', 'None'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('telegram', 'Telegram')], default='none', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='analytics.profile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
