# Generated by Django 6.0.7 on 2026-10-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_profile_location_profileemail_profilephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_photo_in_pdf',
            field=models.BooleanField(default=True, help_text='Web always shows the photo/placeholder. This only controls whether it appears in the downloadable PDF.'),
        ),
    ]
