# Generated by Django 6.0.7 on 2026-10-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_profile_show_photo_in_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedcvpdf',
            name='last_scale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedcvpdf',
            name='last_signature_margin_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cachedcvpdf',
            name='pdf_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
