# Generated by Django 6.0.7 on 2026-07-18 15:11

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('case_study', 'Case Study'), ('blog_post', 'Blog Post'), ('adr', 'ADR')], max_length=20)),
                ('source_id', models.IntegerField(help_text='ID of the CaseStudy/BlogPost/ADR this chunk came from')),
                ('chunk_text', models.TextField(help_text='The actual text chunk that was embedded')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='Vector representation of chunk_text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
