version: 2
models:
  - name: silver_so_survey_historical
    columns:
      - name: survey_year
        tests:
          - not_null
      - name: country
        tests:
          - not_null
      - name: canonical_tool
        tests:
          - not_null
      - name: tool_category
        tests:
          - not_null
          - accepted_values:
              values: ['language', 'database', 'platform']
  - name: silver_practical_data_survey
    columns:
      - name: respondent_id
        tests:
          - unique
          - not_null
      - name: role
        tests:
          - not_null
  - name: silver_ai_jobs_salaries
    columns:
      - name: work_year
        tests:
          - not_null
      - name: experience_level
        tests:
          - not_null
          - accepted_values:
              values: ['EN', 'MI', 'SE', 'EX']
      - name: employment_type
        tests:
          - not_null
          - accepted_values:
              values: ['CT', 'FL', 'FT', 'PT']
      - name: salary_in_usd
        tests:
          - not_null
      - name: remote_ratio
        tests:
          - not_null
          - accepted_values:
              values: [0, 50, 100]
      - name: company_size
        tests:
          - not_null
          - accepted_values:
              values: ['S', 'M', 'L']