version: 2
sources:
  - name: bronze
    schema: bronze
    tables:
      - name: adzuna_job_market
      - name: so_survey_by_country
      - name: so_survey_preferred_global
      - name: github_repo_snapshot
      - name: github_org_snapshot
      - name: arxiv_snapshot
      - name: hackernews_snapshot
      - name: oss_insight_stargazers
      - name: so_survey_historical
      - name: practical_data_survey_2026