from django.urls import path
from .views import (
    CareerArchetypeView, CareerFitView, CountryGrowthForecastView, GrowthForecastStatusView, JobMarketView, MomentumStatusView, NewsKPISummaryView, NewsKeywordBreakoutView, NewsKeywordGrowthView, NewsKeywordListView, NewsKeywordMentionsView, NewsSentimentTrendView, OssLandscapeSummaryView, SalaryForecastMultiyearView, SalaryKPISummaryView, SalaryPredictorMetaView, SalaryPredictorView, SalaryToolListView, SentimentVsAdoptionGapView, SkillSalaryGrowthView, ToolMomentumView, ToolUsageView, ToolPreferenceGlobalView, LastRefreshedView, PipelineRunListView,
    GitHubRepoRankingView, GitHubCohortTrendView, GitHubPlatformComparisonView, GitHubOrgActivityView,
    AgentDiagnosisCreateView, AgentDiagnosisListView, DataQualityActionCreateView, DataQualityActionListView,
    ResearchSignalListView, ToolAdoptionTrendListView, AgentActivitySummaryView,
    AIAdoptionForecastView, VisitorCountView, VisitorHeartbeatView, VisitorStatsView, CountryAISignalView, CountryArchetypeView,
    DeToolSummaryView, DeToolByCountryView, OrgArchetypeSummaryView, CountryToolSignalView, ToolListView, SalaryByToolView, NewsArticleFeedView,
)

urlpatterns = [
    path('career-fit/', CareerFitView.as_view(), name='career-fit'),
    path('job-market/', JobMarketView.as_view(), name='job-market'),
    path('tool-usage/', ToolUsageView.as_view(), name='tool-usage'),
    path('tool-preference-global/', ToolPreferenceGlobalView.as_view(), name='tool-preference-global'),
    path('last-refreshed/', LastRefreshedView.as_view(), name='last-refreshed'),
    path('pipeline-runs/', PipelineRunListView.as_view(), name='pipeline-runs'),
    path('github-repos/', GitHubRepoRankingView.as_view(), name='github-repos'),
    path('github-cohort-trend/', GitHubCohortTrendView.as_view(), name='github-cohort-trend'),
    path('github-platforms/', GitHubPlatformComparisonView.as_view(), name='github-platforms'),
    path('github-orgs/', GitHubOrgActivityView.as_view(), name='github-orgs'),
    path('ai-adoption-forecast/', AIAdoptionForecastView.as_view(), name='ai-adoption-forecast'),
    path('visitor-heartbeat/', VisitorHeartbeatView.as_view(), name='visitor-heartbeat'),
    path('visitor-count/', VisitorCountView.as_view(), name='visitor-count'),
    path('visitor-stats/', VisitorStatsView.as_view(), name='visitor-stats'),
    path('country-ai-signal/', CountryAISignalView.as_view(), name='country-ai-signal'),
    path('country-archetype/', CountryArchetypeView.as_view(), name='country-archetype'),
    path('de-tool-summary/', DeToolSummaryView.as_view(), name='de-tool-summary'),
    path('de-tool-by-country/', DeToolByCountryView.as_view(), name='de-tool-by-country'),
    path('org-archetype-summary/', OrgArchetypeSummaryView.as_view(), name='org-archetype-summary'),
    path('oss-landscape-summary/', OssLandscapeSummaryView.as_view(), name='oss-landscape-summary'),
    path('sentiment-vs-adoption-gap/', SentimentVsAdoptionGapView.as_view(), name='sentiment-vs-adoption-gap'),
    path('country-tool-signal/', CountryToolSignalView.as_view(), name='country-tool-signal'),
    path('growth-forecast-status/', GrowthForecastStatusView.as_view(), name='growth-forecast-status'),
    path('momentum-status/', MomentumStatusView.as_view(), name='momentum-status'),
    path('country-growth-forecast/', CountryGrowthForecastView.as_view(), name='country-growth-forecast'),
    path('tool-list/', ToolListView.as_view(), name='tool-list'),
    path('tool-momentum/', ToolMomentumView.as_view(), name='tool-momentum'),
    path('salary-kpi-summary/', SalaryKPISummaryView.as_view(), name='salary-kpi-summary'),
    path('salary-tool-list/', SalaryToolListView.as_view(), name='salary-tool-list'),
    path('salary-by-tool/', SalaryByToolView.as_view(), name='salary-by-tool'),
    path('skill-salary-growth/', SkillSalaryGrowthView.as_view(), name='skill-salary-growth'),
    path('salary-forecast-multiyear/', SalaryForecastMultiyearView.as_view(), name='salary-forecast-multiyear'),
    path('career-archetype-salary/', CareerArchetypeView.as_view(), name='career-archetype-salary'),
    path('salary-predictor-meta/', SalaryPredictorMetaView.as_view(), name='salary-predictor-meta'),
    path('salary-predictor/', SalaryPredictorView.as_view(), name='salary-predictor'),
    path('news-kpi-summary/', NewsKPISummaryView.as_view(), name='news-kpi-summary'),
    path('news-keyword-list/', NewsKeywordListView.as_view(), name='news-keyword-list'),
    path('news-keyword-mentions/', NewsKeywordMentionsView.as_view(), name='news-keyword-mentions'),
    path('news-sentiment-trend/', NewsSentimentTrendView.as_view(), name='news-sentiment-trend'),
    path('news-keyword-growth/', NewsKeywordGrowthView.as_view(), name='news-keyword-growth'),
    path('news-keyword-breakout/', NewsKeywordBreakoutView.as_view(), name='news-keyword-breakout'),
    path('news-articles/', NewsArticleFeedView.as_view(), name='news-articles'),
    path('agent-diagnosis/', AgentDiagnosisCreateView.as_view(), name='agent-diagnosis-create'),
    path('agent-diagnosis-log/', AgentDiagnosisListView.as_view(), name='agent-diagnosis-list'),
    path('data-quality-action/', DataQualityActionCreateView.as_view(), name='data-quality-action-create'),
    path('data-quality-log/', DataQualityActionListView.as_view(), name='data-quality-list'),
    path('research-signals/', ResearchSignalListView.as_view(), name='research-signals'),
    path('tool-adoption-trends/', ToolAdoptionTrendListView.as_view(), name='tool-adoption-trends'),
    path('agent-activity-summary/', AgentActivitySummaryView.as_view(), name='agent-activity-summary'),
]