# Generated by Django 6.0.7 on 2026-10-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_remove_rest_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='sleep_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
