CREATE ROLE readonly_user WITH LOGIN PASSWORD 'readonlypass123';
GRANT CONNECT ON DATABASE portfolio TO readonly_user;
GRANT USAGE ON SCHEMA public TO readonly_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly_user;